name: React App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install package
      run: yarn install
      
    - name: copy Env
      run: cp /home/.env /var/www/actions-runner/_work/react/react/build
      
    - name: Build React app
      run: yarn build --silent
      env:
        CI: FALSE
        
  deploy:
  
    runs-on: self-hosted

    steps:
      - name: Deploy to Apache
        run: cp /home/.htaccess /var/www/actions-runner/_work/react/react/build
      
      
