name: React App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
      
    - name: Install package
      run: yarn

    - name: Build React app
      run: yarn build

    - name: Run tests
      run: npm test

    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: main
        folder: build

