name: React App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: installing yarn
      run: npm install yarn -g
      
    - name: Install package
      run: yarn install

    - name: Build React app
      run: yarn build
